Update the deploy script and `.git*` files to ignore composer, vendor and other developer files
woocommerce/woocommerce-gateway-paypal-express-checkout pull request #729
Opened 2020-05-12 05:42 UTC by mattallan

With the introduction of using `composer install` to run `phpcs` (see #719), this PR makes sure we don't accidentally deploy or push up any composer or other developer files.

Changes:

 - adds `composer.lock` to .gitignore 
 - adds `composer.lock`, `composer.json`, `vendor`, `.gitattributes` and `.editorconfig` to the list of ignored files/directories when copying files over to the .org SVN
 - adds export-ignore flags for `composer.json`, `composer.lock`, `vendor/` and `.editorconfig` in the `.gitattributes` file

2020-05-13 19:27 UTC, jorgeatorres commented
Hi @mattallan!

Thanks for submitting this 🐈 .
Could you add ".github" (and maybe "wordpress_org_assets") to the `.gitattributes` export-ignore? Other than that, this looks good.

2020-05-13 19:27 UTC, jorgeatorres requested changes
Hi @mattallan!

Thanks for submitting this 🐈 .
Could you add ".github" (and maybe "wordpress_org_assets") to the .gitattributes export-ignore? Other than that, this looks good.

2020-05-14 06:14 UTC, mattallan commented
Hi @jorgeatorres 😄Thanks for the review! I've added both the `.github` and `wordpress_org_assets` directories to the `.gitattributes` file

2020-05-15 01:48 UTC, jorgeatorres approved these changes
Changes look good @mattallan. Thanks! 💯
LGTM 😼 .

2020-05-15 01:48 UTC, merged

2020-09-02 03:42 UTC, Nutza97 approved these changes